### ISSUE TITLE
老铁 666 star 真多 Google 都被干下去了😂

### ISSUE THREAD

**Issue by lioliy** [fuckcqcs/fuckcqcs#109]
老铁 666 日榜周榜 develops 里的 Top 1
![C8CA9EC58BD52CAEE87592BC4240C286.jpg](https://i.loli.net/2018/07/24/5b56a653f2abe.jpg)

repo里的top1也指日可待了👍

**Comment by xunzhaoxusanduo** [comment]
star支持一下

**Comment by junpassion** [comment]
star支持一下
