### ISSUE TITLE
需要详细的流向数据，以进行流向可视化

### ISSUE THREAD

**Issue by massyao** [fuckcqcs/fuckcqcs#111]
根据项目提供的数据，以及新闻中提供的数据，对各疫苗公司及其无效疫苗的历年流向做了可视化，演示地址：http://www.china-invalid-vaccine-flow.cf

项目地址： https://github.com/massyao/china-invalid-vaccine-flow

由于缺乏详细的流向数据，个人会持续关注并更新数据，也希望关注这个事件的朋友寻找数据，让这个事件更加清楚

**Comment by fuckcqcs** [comment]
感谢
