### ISSUE TITLE
请勿在 Issues 页面无意义灌水，此类行为属于对 Issues 区的滥用。

### ISSUE THREAD

**Issue by Fazx** [fuckcqcs/fuckcqcs#127]
请勿在 Issues 页面无意义灌水，此类行为属于对 Issues 区的滥用。

可能有很多人是从这件事加入GitHub，Issues区竟然出现了大量如“老铁666”这样毫无意义的灌水内容。

> Issues are a great way to keep track of tasks, enhancements, and bugs for your projects. 

-[Mastering Issues](https://guides.github.com/features/issues/) 

GitHub是一个全球共享的技术社区，你可以在Issues中提交新的**数据来源，程序建议或bug fixes**，但请不要把Issues功能当做**微博评论或贴吧回贴**，你在社区的中文发言都代表着华人的形象。

**Comment by dilfish** [comment]
说这些都没啥用的，issue 没有权限管理。
写个 js 脚本批量关就行。
关心的都提 pr 了，谁闲的灌水。
别动不动就代表华人形象啦。感觉你们年轻人好激动，做这么个数据库的影响没你想的那么大，灌灌水的坏处也没你想的那么多。

**Comment by Fazx** [comment]
@dilfish 您说得有道理  BTW感觉您的博客很有趣 😋
