### ISSUE TITLE
有没有必要准备英文版的README.md？

### ISSUE THREAD

**Issue by BlazeRedlip007** [fuckcqcs/fuckcqcs#133]
看了一下，内容全部是中文的。作为本周Trending开发者排在高位的项目（[https://github.com/trending/developers](https://github.com/trending/developers)），有没有必要考虑用英文说明一下发生了什么事情？

**Comment by baiyyang** [comment]
我觉得可以。。。。

**Comment by fuckcqcs** [comment]
有兴趣可以提PR。
看得懂英文
但是不会写。

**Comment by osoc** [comment]
建议不要了，这不是光彩的事情。当然，搞新闻的老外，中文他们也看得懂。
