### ISSUE TITLE
关于内蒙古的csv

### ISSUE THREAD

**Issue by Laplacence** [fuckcqcs/fuckcqcs#138]
155-157 name src不明确 需要更改
以及243项开始没有右括号（强迫症难受

**Comment by Laplacence** [comment]
而且广西的数据已经整理完毕了

**Comment by nxsnow** [comment]
中间那块我脚本好像碰到了什么诡异的字符，被断掉了。
然后那个括号。。本来数据源就那样

**Comment by Laplacence** [comment]
对比过原数据后 发现是有合并单元格然后转csv的时候出了问题 已经修正 谢谢！
