### ISSUE TITLE
如何能更长期有效的收集数据

### ISSUE THREAD

**Issue by lanxx019** [fuckcqcs/fuckcqcs#139]
感觉现在收集数据的渠道非常有限，数据的窗口很小，很多地方的数据基本没有什么代表性。是否有更好的收集数据的渠道。特别是历史的旧数据。

本人不在国内，所以对一些事情不是很了解。希望大家多提建议。

**Comment by nxsnow** [comment]
感觉还是挺难的。每个省的数据格式出入极大,国家也没有一个统一的数据库。美国这边CDC都是有现成数据库的。

**Comment by Laplacence** [comment]
而且此次事件之后 不知道会封锁/修改数据还是更加透明化。。。

**Comment by catalinamei** [comment]
CDC有 内部系统 不对外

**Comment by fuckcqcs** [comment]
我也母鸡啊
