### ISSUE TITLE
联络转载

### ISSUE THREAD

**Issue by Icy-lucky** [fuckcqcs/fuckcqcs#14]
作者你好，我是澎湃新闻的记者，联络希望能够在平台转载，烦请联系我，谢谢！邮箱：wuyt@thepaper.cn   微信：15901972467

**Comment by iMLe0n** [comment]
干嘛把自己的信息放上去。。。

**Comment by Smallyo** [comment]
记者一个比一个跑的快

**Comment by CFM880** [comment]
中华人民共和国药品管理法第五条

 国务院药品监督管理部门主管全国药品监督管理工作。国务院有关部门在各自的职责范围内负责与药品有关的监督管理工作。

**省、自治区、直辖市人民政府药品监督管理部门负责本行政区域内的药品监督管理工作。省、自治区、直辖市人民政府有关部门在各自的职责范围内负责与药品有关的监督管理工作。**

国务院药品监督管理部门应当配合国务院经济综合主管部门，执行国家制定的药品行业发展规划和产业政策。

想发觉新闻点，请看加粗的文字。

**Comment by CFM880** [comment]
中华人民共和国药品管理法第八章第六十四条

国务院和**省、自治区、直辖市人民政府的药品监督管理部门**应当定期公告药品质量抽查检验的结果；公告不当的，必须在原公告范围内予以更正。
