### ISSUE TITLE
建议将中文版README置于首页

### ISSUE THREAD

**Issue by HurryPeng** [fuckcqcs/fuckcqcs#148]
鉴于本事件主要关乎国内，且关注者大多为华人，建议将中文版README置于首页，并在标题附近保留英文版链接，以供国际接轨之需。首页上直接展示的中文README能够快速引起华人群体的注意，有利于扩大影响力。

**Comment by Freakwill** [comment]
上github的华人，英语应该没问题。

**Comment by HurryPeng** [comment]
但母语能给人一种“这与我有关”的第一印象，何况这个事件并没有必要用英文讨论。

**Comment by cx-emerge** [comment]
支持优先显示中文的方案，这并不是一个国际项目，项目只是方便国内人的查阅

**Comment by BlazeRedlip007** [comment]
没有吧

**Comment by HurryPeng** [comment]
中文版README上面那个English的shield链接还没改过来呀
