### ISSUE TITLE
csv乱码

### ISSUE THREAD

**Issue by HiDuke** [fuckcqcs/fuckcqcs#150]

**Comment by Andersonfeng** [comment]
### 目前有两种解决方案
- 是用记事本类的工具打开
- 用Excel的"自文本"导入数据
    - 打开Excel
    - 选择标题栏的"数据"-"自文本",在弹出的框中选择乱码的CSV![image](https://user-images.githubusercontent.com/13361365/43175688-e5977d02-8ff2-11e8-8c2c-4cfeba322980.png)
    - 在文本中,看到csv中的数据是用逗号(,)隔开的,选择"分隔符号",点击"下一步"
![image](https://user-images.githubusercontent.com/13361365/43175549-4abff516-8ff2-11e8-90b6-e46c753ebf62.png)
    - 在第二步中选择"逗号",并点击"完成"和"确定"即可 ![image](https://user-images.githubusercontent.com/13361365/43175600-81b00e76-8ff2-11e8-950f-3d38366415c6.png)
![image](https://user-images.githubusercontent.com/13361365/43175663-cbfe3624-8ff2-11e8-8299-3095c78e55e7.png)

**Comment by Andersonfeng** [comment]
@Laplacence 
好的,这就开多个issues

**Comment by Laplacence** [comment]
@Andersonfeng
已看到/+1 感谢！
