### ISSUE TITLE
我们也在做类似的事情，希望可以建立联系谢谢

### ISSUE THREAD

**Issue by gaoxiaos** [fuckcqcs/fuckcqcs#158]
q  534011382

**Comment by fuckcqcs** [comment]
数据都在 自行获取

**Comment by gaoxiaos** [comment]
能给个联系方式么




| |
13058037784
邮箱：13058037784@163.com
|

Signature is customized by Netease Mail Master

在2018年07月25日 19:36，fuckcqcs 写道：

数据都在 自行获取

**Comment by gaoxiaos** [comment]
你好，我是阿里云飞天一部的岱月，我想邀请阿里云天池的开发者来参与你的项目，上传更多的数据，并提供1万元的奖金支持，不知道你是否OK？能加微信聊一下吗？如果你感兴趣请联系我：）







岱月
阿里云－飞天一部－天池平台
| |
13058037784
邮箱：13058037784@163.com
|

Signature is customized by Netease Mail Master

在2018年07月25日 19:36，fuckcqcs 写道：

数据都在 自行获取
