### ISSUE TITLE
数据是一方面，建议把一些深度分析的信息也放进去

### ISSUE THREAD

**Issue by jevinsu** [fuckcqcs/fuckcqcs#19]
例如这篇文章：
http://www.bjnews.com.cn/opinion/2018/07/22/496219.html

我们这个国家总是不停地出现这个天灾那个人祸，黑色的事件层出不穷，不是靠英明领导领导所谓彻查或者网络高手收集一堆精准数据就能解决的...

**Comment by weaming** [comment]
有几个想法

1. 给出数据来源
1. 给出转换代码
1. 这些数据有哪些分析价值？

欢迎讨论

**Comment by DAangel101** [comment]
还是态度问题，设卡检查，大官给你一巴掌，检查的人就不检查了。
