### ISSUE TITLE
江苏的数据打不开

### ISSUE THREAD

**Issue by knightgao** [fuckcqcs/fuckcqcs#2]
显示已经损坏

**Comment by smilefishes** [comment]
会不会是excel问题？我这边打开正常。
macOS 10.13.6
Microsoft EXCEL 15.13.3(150815)

**Comment by tanmx** [comment]
可以正常打开

**Comment by lzh85661** [comment]
excel打开乱码，记事本打开能看见字。

**Comment by lzh85661** [comment]
original文库里的还能看见https://wenku.baidu.com/view/9a93a060a88271fe910ef12d2af90242a895abf3.html
