### ISSUE TITLE
补充山东省数据和青海省部分数据

### ISSUE THREAD

**Issue by wydwww** [fuckcqcs/fuckcqcs#4]
[关于公布 2016 年山东省第二类疫苗集中采购合格生产企业及产品的通知](http://www.sdyypt.net/Website/newsshow.aspx?id=f8598ce4-86e0-41d1-8532-95546d2cb9f5)
[关于公布第二类疫苗集中采购新增合格生产企业及产品（第一批）的通知](http://www.sdyypt.net/Website/newsshow.aspx?id=1bdb0e89-ea33-4909-92f3-547d5683d46a)
[关于公布 2017 年第二类疫苗集中采购新增合格生产企业及产品（第二批）的通知](http://www.sdyypt.net/Website/newsshow.aspx?id=28b53fa5-f15a-4933-b1c6-365a17b84780)
当中附有山东省企业和产品名单

[关于公布青海省第二类疫苗集中采购申报企业资质审核合格企业名单的通知](http://223.220.250.135:8081/HomePage/ShowDetail.aspx?InfoId=186)
这个文件是青海省 2017 年唯一公开的企业名单

**Comment by uivplusu** [comment]
你好，我是南都的记者，方便联系一下吗？我的邮箱是uivplusu@163.com

**Comment by xiangyangluntan** [comment]
建议使用Gmail邮箱！安全些！
