### ISSUE TITLE
可不可以提个PR把V2上的帖子保存到README里面？

### ISSUE THREAD

**Issue by athrunsun** [fuckcqcs/fuckcqcs#5]
我想提个PR把[V2上的帖子](https://www.v2ex.com/t/473163)保存到README里面，发在国内的帖子可能会被ban，那样就可惜了。

**Comment by athrunsun** [comment]
PR已经提了 #7

**Comment by funny110** [comment]
保存到[ZeroNet](https://github.com/HelloZeroNet/ZeroNet/blob/master/README-zh-cn.md)永远不会被任何人ban
