### ISSUE TITLE
CSV部分下载下来是乱码的，其他正常

### ISSUE THREAD

**Issue by Fatyuan221** [fuckcqcs/fuckcqcs#59]
CSV部分下载下来是乱码的，其他正常。感谢！

**Comment by bushadie** [comment]
用记事本打开,另存为, 选择编码为  Unicode  就不乱码了.
但csv的格式还是乱的...........  用excel处理一下就行

**Comment by summerchu24** [comment]
可以用excel处理，打开方式选择用文本方式，文件原始格式选择Unicode 9.0 UTF-7/8

**Comment by jiacai-wang** [comment]
VS code打开csv正常啊

**Comment by fuckcqcs** [comment]
VS code 正解
