### ISSUE TITLE
疫苗来源属于国产/进口的分类参考材料

### ISSUE THREAD

**Issue by kikiyang** [fuckcqcs/fuckcqcs#62]
可以上传一下各个生产厂家是进口还是国产的表格吗？这样帮着整理数据的话，可以避免重复性工作而且能统一标准。

**Comment by kikiyang** [comment]
我查了一下，根据[中国食品药品检定研究院2017 年生物制品批签发年报](http://www.nifdc.org.cn/directory/web/WS02/images/uL28iAyMDE3xOrJ+s7v1sbGt8X6x6m3osTqsagucGRm.pdf)的表3：
[2017年取得进口药品注册证医药产品注册证疫苗品种签发情况.xlsx](https://github.com/fuckcqcs/fuckcqcs/files/2218937/2017.xlsx)

只有表中6家公司的11种疫苗的部分批次是进口疫苗。作者的csv数据里国产和进口的分类有需要修改的吗？

**Comment by fuckcqcs** [comment]
有的政府有写国产还是国外 
有些没有，
有的话就标记了国产国外
否则一律标记成国内 这是数据不严谨的地方。
