### ISSUE TITLE
并不赞成po主这样做

### ISSUE THREAD

**Issue by gemini5044** [fuckcqcs/fuckcqcs#64]
github本是技术社区，在这里讨论社会政治问题会给社区带来不必要的麻烦，比如被那道长长的城墙挡在外面

**Comment by xuyz** [comment]
事情是好的，不过真不赞成在github上做。

**Comment by o03150** [comment]
这是公开数据,怕毛线

**Comment by yenkeia** [comment]
参考上次[北大岳昕事件](https://github.com/sikaozhe1997/Xin-Yue/issues/530)

**Comment by hidoos** [comment]
自我审查这么爽么？

**Comment by RolarWang** [comment]
1、这是一个开放的平台，在不违”法“的前提下，po主想发布什么发布什么；2、为什么在这里发布，你我心里都有数；3、你的出发点跟”担心会被连累就闭嘴不发声，保全自己就好“有啥区别？？？

**Comment by fan123199** [comment]
这不是政治问题， 这就是个处理数据的技术项目
