### ISSUE TITLE
支持，不过移步到国内社区比较好，还是要保护一下github，它是国内程序员通往世界唯一的窗口了

### ISSUE THREAD

**Issue by WALL-E** [fuckcqcs/fuckcqcs#65]

**Comment by Mickiman** [comment]
github被墙的话  大家都不搞梯子了，合伙拆墙

**Comment by chengshijie1997** [comment]
国内获取消息的方式少的太可怜了，各个网站随时可能被ban，微博说删贴就删。对于消息没什么可靠的传播途径了。

**Comment by valord577** [comment]
迁移国内？你不会想去找作者是谁吧？

**Comment by ezhyg** [comment]
既然都是翻墙了，留一把梯子有何意义。

**Comment by lqdflying** [comment]
脑残+自私，放国内作者分分钟被干，代码被删。
干程序员干到只有这一个窗口，也就别干了。到死也是个码畜

**Comment by lqdflying** [comment]
有的程序员为大家写了一套梯子，有的程序员为了能访问github求gfw不要墙掉梯子——前边的人就算不为维护代码了，也永远成为大家心目中的大佬，后者到死，都是个被洗脑到残的码畜

**Comment by fuckcqcs** [comment]
国内的代码库，需要验证手机号。

**Comment by vsTianhao** [comment]
只要不评论就不会有问题的，大家太敏感了
