### ISSUE TITLE
可不可以去ZeroNet开个网站，保存记录这些数据？

### ISSUE THREAD

**Issue by funny110** [fuckcqcs/fuckcqcs#8]
这是别人转过去的 http://127.0.0.1:43110/lastone.bit/?Post:41
[截图](https://i.loli.net/2018/07/23/5b554ba1303f9.png)

另外，ZeroNet在这里https://github.com/HelloZeroNet/ZeroNet
https://github.com/HelloZeroNet/ZeroNet/blob/master/README-zh-cn.md

**Comment by yoyokko** [comment]
谷歌快照有的，我贴上来

**Comment by funny110** [comment]
@0312birdzhang 好像你没有发布。打不开

**Comment by funny110** [comment]
@0312birdzhang 现在看到了，已帮做种

**Comment by 0312birdzhang** [comment]
@funny110 嗯，手动设置了代理才可以了。

**Comment by Godlys** [comment]
666,ZeroNet是个不错的想法，但是网站大小有限制，建议可以将数据全部存储成json，之后下载的时候，通过代码转成表格
