### ISSUE TITLE
pandas解析的时候注意下编码，不然excl会出现中文乱码

### ISSUE THREAD

**Issue by Duukeee** [fuckcqcs/fuckcqcs#89]
另外地市数据其实也可以索引到，有必要可以开个爬虫

**Comment by fuckcqcs** [comment]
p3 还好。
p2 已经废弃了

**Comment by Duukeee** [comment]
开发环境p3.6.5 + pandas 0.22.0 ，不太清楚你的csv转换实现，但是csv编码是unicode 一般用excl肯定是乱码，方便非程序猿阅读，建议生成添加一下encode格式。当然用VSC这类打开肯定是没有问题的。
