### ISSUE TITLE
关于江西省2018的疑惑？

### ISSUE THREAD

**Issue by clearcodecn** [fuckcqcs/fuckcqcs#93]
```
defer func(){
     我的问题是：江西省的这批药到底是采购了但是江西台否认了，  还是说采购的药是没问题的。
}
```
刚刚看到江西二台都市现场权威发布说，内容大致如下：

都市现场
江西省疾控中心回应：未采购涉事批次疫
苗
7月15日国家药品监督管理局发布通告，在对长
春长生生物科技有限责任公司开展飞行检查时，
发现该企业冻干人用狂犬病疫苗生产存在记录造
假等严重违反《药品生产质量管理规范》行为。
本次飞行检査所有涉事批次产品尚未出厂和上市
销售，全部产品已得到有效控制。江西省未米
购涉事批次疫苗。
2017年11月3日国家食品药品监管总局公布了在
药品抽样检验中检出长春长生生物科技有限责任
公司生产的批号201605014－01的百白破疫苗效
价指标不符合标准规定。经核实，江西省未
采购该公司生产的该批次百白破疫苗

**Comment by xcaptain** [comment]
http://jiangxi.jxnews.com.cn/system/2018/07/22/017028370.shtml

找到新闻源了，不过这些官老爷说的话也做不得准

**Comment by maskleo** [comment]
这次并不单是疫苗的事情了，十年前的三聚氰胺的阴影还没走出来，现在又出现这个，那么下一个是什么？什么是真的，什么又是假的，这才可怕！！！

**Comment by clearcodecn** [comment]
问一下 @fuckcqcs excel中的数据是从哪里采集的，能否公布一下看看。

**Comment by fuckcqcs** [comment]
https://github.com/fuckcqcs/fuckcqcs/blob/master/README.md
